- name: Create a new Server
  hosts: localhost

  tasks:
    - name: Generate SHA-512 password hash
      ansible.builtin.set_fact:
        SUDO_PASSWORD_HASH: "{{ SUDO_PASSWORD | password_hash('sha512') }}"
      no_log: true

    # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/server_module.html#ansible-collections-hetzner-hcloud-server-module
    - name: Create a new Server
      hetzner.hcloud.server:
        state: present
        api_token: "{{ HETZNER_API_TOKEN }}"
        backups: "{{ BACKUPS }}"
        image: "{{ IMAGE }}"
        name: "{{ NAME }}"
        datacenter: "{{ DATACENTER }}"
        server_type: "{{ SERVER_TYPE }}"
        ssh_keys: "{{ HETZNER_SSH_KEYS }}"
        user_data: "{{ lookup('template', 'templates/cloud-config.yml.j2') }}"
      register: created_vps

    - name: Debug template output
      debug:
        msg: "{{ lookup('template', 'templates/cloud-config.yml.j2') }}"

    - name: Custom output for created server
      debug:
        msg: |
          <server-response>{{ created_vps | to_json }}</server-response>

    - name: Assert that the server was created successfully
      assert:
        that:
          - created_vps.failed is false
          - created_vps.hcloud_server is defined
        fail_msg: "Server creation failed"
        success_msg: "Server created successfully"
