#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=4

# Outside the repository, so every worktree and build session reads the same file.
ENV_FILE="$HOME/.config/alfredo/build.env"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

banner "Alfredo build: real server, domain, and Purelymail"

# ── Stage 1: the server ───────────────────────────────────────────────────
stage "Real server"
say "The build needs one Ubuntu 24.04 server with a public address."
say "Build sessions connect over SSH with a key and no passphrase prompt."
step "Create the server at your provider, or pick one that holds nothing you need."
step "Add your SSH public key to a user that can run sudo without a password."
ask ALFREDO_SERVER_HOST "Public IPv4 address of the server:"
ask ALFREDO_SERVER_SSH_USER "SSH user (for example root):"
ask ALFREDO_SERVER_SSH_PORT "SSH port (for example 22):"
ask ALFREDO_SERVER_SSH_KEY "Path to the SSH private key (for example $HOME/.ssh/id_ed25519):"
write_env ALFREDO_SERVER_HOST "$ALFREDO_SERVER_HOST"
write_env ALFREDO_SERVER_SSH_USER "$ALFREDO_SERVER_SSH_USER"
write_env ALFREDO_SERVER_SSH_PORT "$ALFREDO_SERVER_SSH_PORT"
write_env ALFREDO_SERVER_SSH_KEY "$ALFREDO_SERVER_SSH_KEY"
say "Checking the connection and the operating system..."
if os=$(ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new \
      -i "$ALFREDO_SERVER_SSH_KEY" -p "$ALFREDO_SERVER_SSH_PORT" \
      "$ALFREDO_SERVER_SSH_USER@$ALFREDO_SERVER_HOST" \
      '. /etc/os-release && echo "$PRETTY_NAME"' 2>&1); then
  printf '  %s✓ connected%s: %s\n' "$GREEN" "$RESET" "$os"
  [[ "$os" == *"24.04"* ]] || warn "the specs expect Ubuntu 24.04"
else
  warn "SSH failed: $os"
  SKIPPED+=("SSH access to the server (fix it, then re-run this wizard)")
fi
pause

# ── Stage 2: the domain ───────────────────────────────────────────────────
stage "Domain and DNS"
say "HTTPS tests need a domain that points at the server."
say "Use a domain or subdomain that serves nothing else, such as alfredo-test.example.com."
ask ALFREDO_TEST_DOMAIN "Test domain:"
write_env ALFREDO_TEST_DOMAIN "$ALFREDO_TEST_DOMAIN"
step "At your DNS provider, create these two records:"
say "    A   $ALFREDO_TEST_DOMAIN     →  $ALFREDO_SERVER_HOST"
say "    A   *.$ALFREDO_TEST_DOMAIN   →  $ALFREDO_SERVER_HOST"
note "The wildcard gives HQ and each test project its own hostname."
note "If your provider proxies traffic, turn the proxy off for both records."
pause "Press Enter when both records exist"
for name in "$ALFREDO_TEST_DOMAIN" "wizard-check.$ALFREDO_TEST_DOMAIN"; do
  got=$(getent ahostsv4 "$name" 2>/dev/null | awk 'NR==1{print $1}' || true)
  if [[ "$got" == "$ALFREDO_SERVER_HOST" ]]; then
    printf '  %s✓%s %s resolves to %s\n' "$GREEN" "$RESET" "$name" "$got"
  else
    warn "$name resolves to '${got:-nothing}', expected $ALFREDO_SERVER_HOST"
    SKIPPED+=("DNS for $name (it can take a few minutes; re-run to check again)")
  fi
done
pause

# ── Stage 3: Purelymail ───────────────────────────────────────────────────
stage "Purelymail API token"
say "The Purelymail Tray needs the account's API token."
warn "The token has access to the whole Purelymail account."
open_url "https://purelymail.com/manage/account"
step "Sign in, then find the API section of the account settings."
step "Create or refresh the API key, and copy it."
note "If the page layout differs, look for 'API' in the account settings."
ask_secret PURELYMAIL_API_TOKEN "Paste the API token:"
write_env PURELYMAIL_API_TOKEN "$PURELYMAIL_API_TOKEN"

# ── Stage 4: test mail domain ─────────────────────────────────────────────
stage "Test mail domain"
say "Tray tests add and delete a mail domain, and deleting a domain deletes its mailboxes."
say "Name a domain or subdomain that holds no real mail, such as mail.$ALFREDO_TEST_DOMAIN."
note "You don't need to add it to Purelymail. The tests do that through the API."
ask PURELYMAIL_TEST_MAIL_DOMAIN "Test mail domain:"
write_env PURELYMAIL_TEST_MAIL_DOMAIN "$PURELYMAIL_TEST_MAIL_DOMAIN"

chmod 600 "$ENV_FILE"
finish
