#!/usr/bin/env bun
import path from "path";
import { existsSync } from "fs";
import { rm } from "fs/promises";

const TARGETS = {
  "linux-x64": "bun-linux-x64",
  "linux-arm64": "bun-linux-aarch64",
  "darwin-x64": "bun-darwin-x64",
  "darwin-arm64": "bun-darwin-aarch64",
} as const;

type TargetKey = keyof typeof TARGETS;

const targetArg = process.argv.find((a) => a.startsWith("--target="))?.split("=")[1] as
  | TargetKey
  | undefined;

if (targetArg && !(targetArg in TARGETS)) {
  console.error(`❌ Unknown target: ${targetArg}`);
  console.error(`   Available: ${Object.keys(TARGETS).join(", ")}`);
  process.exit(1);
}

const target = targetArg ? TARGETS[targetArg] : "bun";
const suffix = targetArg ?? "native";

const outdir = path.join(process.cwd(), "dist");
const outfile = path.join(outdir, `alfredo-${suffix}`);

if (existsSync(outdir)) {
  console.log("🗑️  Cleaning previous build...");
  await rm(outdir, { recursive: true, force: true });
}

console.log(`🚀 Compiling single executable (${suffix})...\n`);

const start = performance.now();

const proc = Bun.spawn(
  [
    "bun",
    "build",
    "--compile",
    "--minify",
    "--sourcemap=none",
    `--target=${target}`,
    "--outfile",
    outfile,
    "src/index.tsx",
  ],
  {
    cwd: process.cwd(),
    stdout: "inherit",
    stderr: "inherit",
    env: {
      ...process.env,
      NODE_ENV: "production",
    },
  },
);

const exitCode = await proc.exited;
const elapsed = (performance.now() - start).toFixed(0);

if (exitCode !== 0) {
  console.error(`\n❌ Compilation failed (exit code ${exitCode})`);
  process.exit(exitCode);
}

// Clean up source maps generated by the bundler
for await (const mapFile of new Bun.Glob("**/*.map").scan(outdir)) {
  await rm(path.join(outdir, mapFile));
}

if (existsSync(outfile)) {
  const size = Bun.file(outfile).size;
  const mb = (size / 1024 / 1024).toFixed(2);
  console.log(
    `\n✅ Compiled in ${elapsed}ms → ${path.relative(process.cwd(), outfile)} (${mb} MB)`,
  );
} else {
  console.log(`\n✅ Compiled in ${elapsed}ms`);
}
